[package]
name = "mireforge-wgpu"
version = "0.0.27"
edition = "2024"
license = "MIT"
description = "wgpu utility functions"
repository = "https://github.com/mireforge/mireforge"
categories = ["game-development"]
keywords = ["game", "render"]

[dependencies]
wgpu = "28.0"
