[package]
name = "mireforge-game-audio"
version = "0.0.26"
edition = "2024"
repository = "https://github.com/mireforge/mireforge"
license = "MIT"
categories = ["game-development"]
description = "Game audio"

[dependencies]
limnus-audio-mixer = "0.0.20"
limnus-assets = "0.0.20"

tracing = "0.1.40"
